Update to 2.3
LorbusChris/rspamd-rpm pull request #15
Opened 2020-02-06 04:43 UTC by kaechele

- changed upstream URL to use a sensible filename
- add lua_content directory
- use %%autosetup macro
- refresh ciphers patch
- add replxx compile fix patch

2020-02-06 13:43 UTC, LorbusChris commented
Thank you!

One Question:
Is there an upstream reference for the new patch? I.e. why is it needed, and will it be fixed upstream? If there is no upstream issue, yet. I'd ask you to file on and reference it in the spec so we can track it.

2020-02-06 15:30 UTC, kaechele commented
https://github.com/AmokHuginnsson/replxx/pull/65

Since it is bundled directly into rspamd we'd also need to inform them as soon as above PR is merged.

2020-02-06 16:40 UTC, LorbusChris requested changes

2020-02-06 16:40 UTC, LorbusChris commented on rspamd.spec
> +%autosetup -p1
if you could add a link to the upstream replxx PR here, I'll merge :)

2020-02-26 17:21 UTC, kaechele commented
2.4 is out. Will resubmit.

2020-02-26 17:21 UTC, closed without merging

2020-02-26 20:22 UTC, LorbusChris commented
thanks!